### ISSUE TITLE
Code Spacing

### ISSUE THREAD

**Issue by hmontero1205** [dpspdx/pwp-capstones#1]
The spacing in your code is a little messy and inconsistent. In general, you want to add a space between items in an expression.

Instead of this: `x=y+1` do this: `x = y + 1`. Just makes everything much more pleasant to look at.
Additionally, a common coding practice is to add a blank link between the return statement and the rest of the code, if the function is relatively flat. That is, if your function kinda looks like this:
```
def func(param):
   #code
   #code
        #code
   #code
   #code
    return param + 1
```
You should separate the return statement from the rest of the code.
```
def func(param):
   #code
   #code
        #code
   #code
   #code

    return param + 1
```

**Comment by dpspdx** [comment]
I will try to improve on this.  Understandable why it is not clean.  Thanks!
