### ISSUE TITLE
Boolean Expressions

### ISSUE THREAD

**Issue by hmontero1205** [dpspdx/pwp-capstones#2]
Throughout your program, you have boolean expressions that are correct, but redundant. Here's one:
```
if self.email == other_user.email and self.name == other_user.name:
   return True
else:
   return False
```

This if-statement is not necessary at all. Look at what you're doing. You're checking to see if that boolean expression is `True` or `False`. If `True`, return `True`. If `False`, return `False`. Checking the value is unnecessary work. Just return the expression.

```
return self.email == other_user.email and self.name == other_user.name
```

**Comment by dpspdx** [comment]
makes 100% sense.  thanks for the feedback
